version: '3.9'

services:
  astrbot:
    image: soulter/astrbot:latest
    container_name: astrbot
    restart: unless-stopped
    environment:
      - TOKEN=${ASTRBOT_TOKEN}  # 在 .env 或 Railway 环境变量中配置
    ports:
      - "6185:6185"
      - "3000:3000"
      - "3001:3001"
      - "11451:11451"

  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    restart: unless-stopped
    environment:
      - CONFIG_PATH=/config  # 根据 napcat 配置需要修改
    volumes:
      - napcat_data:/config
    ports:
      - "6099:6099"

volumes:
  napcat_data:
